# http://www.thisprogrammingthing.com/2015/multiple-vagrant-vms-in-one-vagrantfile/

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  # boxes at https://atlas.hashicorp.com/search.
  # config.vm.box = "ubuntu/trusty64"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.10.14"

  config.vm.define "web3" do |web3|

    web3.vm.box = "ubuntu/trusty64"    
    web3.vm.hostname = 'web3'
    web3.vm.network :private_network, ip: "192.168.56.103"

    web3.vm.provider :virtualbox do |v|
      # v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "web3"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      sudo su
      apt-get update
      apt -y install docker.io
      service docker start
      wget -O /usr/local/bin/weave https://github.com/weaveworks/weave/releases/download/latest_release/weave
      chmod a+x /usr/local/bin/weave
      weave launch 192.168.56.101 192.168.56.102 192.168.56.104
      eval "$(weave env)"
      curl -L git.io/scope -o /usr/local/bin/scope
      chmod a+x /usr/local/bin/scope
      scope launch
      export DOCKER_IP='192.168.56.103'
      docker run -d --net=host --name consul consul agent -bind=$DOCKER_IP -retry-join=192.168.56.104
      docker run -d --name=registrator --net=host --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator:latest consul://127.0.0.1:8500
      weave run 10.2.1.4/24  -d --name play-pin -p 8080:9000 isac/play-pin:1.9
      weave run 10.2.1.1/24 --name cassandra -h cassandra1.weave.local -d -v /data:/var/lib/cassandra -v /../vagrant/cassandra-env.sh:/etc/cassandra/cassandra-env.sh  -e CASSANDRA_LISTEN_ADDRESS=10.2.1.1 -p 7000:7000 cassandra:3.9
    
    SHELL
  end

  config.vm.define "web1" do |web1|

    web1.vm.box = "ubuntu/trusty64"    
    web1.vm.hostname = 'web1'
    web1.vm.network :private_network, ip: "192.168.56.101"

    web1.vm.provider :virtualbox do |v|
      # v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "web1"]
    end
    
    config.vm.provision "shell", inline: <<-SHELL
      sudo su
      apt-get update
      apt -y install docker.io
      service docker start
      wget -O /usr/local/bin/weave https://github.com/weaveworks/weave/releases/download/latest_release/weave
      chmod a+x /usr/local/bin/weave
      weave launch 192.168.56.102 192.168.56.103 192.168.56.104
      eval "$(weave env)"
      curl -L git.io/scope -o /usr/local/bin/scope
      chmod a+x /usr/local/bin/scope
      scope launch
      export DOCKER_IP='192.168.56.101'
      docker run -d --net=host --name consul consul agent -bind=$DOCKER_IP -retry-join=192.168.56.104
      docker run -d --name=registrator --net=host --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator:latest consul://127.0.0.1:8500
      weave run 10.2.1.5/24 -d --name play-pin -p 8080:9000 isac/play-pin:1.9
      weave run 10.2.1.3/24  --name cassandra -h cassandra2.weave.local -d -v /data:/var/lib/cassandra -v /../vagrant/cassandra-env.sh:/etc/cassandra/cassandra-env.sh  -e CASSANDRA_LISTEN_ADDRESS=10.2.1.3  -e CASSANDRA_SEEDS=10.2.1.1 -p 7000:7000 cassandra:3.9

    SHELL
  end

  config.vm.define "web4" do |web4|

    web4.vm.box = "ubuntu/trusty64"    
    web4.vm.hostname = 'web4'
    web4.vm.network :private_network, ip: "192.168.56.102"

    web4.vm.provider :virtualbox do |v|
      # v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "web4"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      sudo su
      apt-get update
      apt -y install docker.io
      service docker start
      wget -O /usr/local/bin/weave https://github.com/weaveworks/weave/releases/download/latest_release/weave
      chmod a+x /usr/local/bin/weave
      weave launch 192.168.56.101 192.168.56.103 192.168.56.104
      eval "$(weave env)"
      curl -L git.io/scope -o /usr/local/bin/scope
      chmod a+x /usr/local/bin/scope
      scope launch
      export DOCKER_IP='192.168.56.102'
      docker run -d --net=host --name consul consul agent -bind=$DOCKER_IP -retry-join=192.168.56.104
      docker run -d --name=registrator --net=host --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator:latest consul://127.0.0.1:8500
      weave run 10.2.1.6/24 -d --name play-pin -p 8080:9000 isac/play-pin:1.9
      weave run 10.2.1.2/24  --name cassandra -h cassandra3.weave.local -d -v /data:/var/lib/cassandra -v /../vagrant/cassandra-env.sh:/etc/cassandra/cassandra-env.sh  -e CASSANDRA_LISTEN_ADDRESS=10.2.1.2  -e CASSANDRA_SEEDS=10.2.1.1 -p 7000:7000 cassandra:3.9

    SHELL
  end

end
