# http://www.thisprogrammingthing.com/2015/multiple-vagrant-vms-in-one-vagrantfile/

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  # boxes at https://atlas.hashicorp.com/search.
  # config.vm.box = "ubuntu/trusty64"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.10.14"

  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/trusty64"    
    web1.vm.hostname = 'web1'
    web1.vm.network :private_network, ip: "192.168.56.101"

    web1.vm.provider :virtualbox do |v|
      # v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "web1"]
    end
    
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt -y install docker.io
      sudo service docker start
      sudo docker pull isac/play-pin:latest
      sudo docker run -d --name play-pin1 -p 8080:9000 isac/play-pin
      sudo docker pull mongo
      sudo docker run -d --name mongo1 -p 30000:27017 mongo mongod --replSet pin-mongo-set
    SHELL
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/trusty64"    
    web2.vm.hostname = 'web2'
    web2.vm.network :private_network, ip: "192.168.56.102"

    web2.vm.provider :virtualbox do |v|
      # v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "web2"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt -y install docker.io
      sudo service docker start
      sudo docker pull isac/play-pin:latest
      sudo docker run -d --name play-pin2 -p 8080:9000 isac/play-pin
      sudo docker pull mongo
      sudo docker run -d --name mongo2 -p 30000:27017 mongo mongod --replSet pin-mongo-set
    SHELL
  end

  config.vm.define "web3" do |web3|
    web3.vm.box = "ubuntu/trusty64"    
    web3.vm.hostname = 'web3'
    web3.vm.network :private_network, ip: "192.168.56.103"

    web3.vm.provider :virtualbox do |v|
      # v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "web3"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt -y install docker.io
      sudo service docker start
      sudo docker pull isac/play-pin:latest
      sudo docker run -d --name play-pin3 -p 8080:9000 isac/play-pin
      sudo docker pull mongo
      sudo docker run -d --name mongo3 -p 30000:27017 mongo mongod --replSet pin-mongo-set
    SHELL
  end

end
