# http://www.thisprogrammingthing.com/2015/multiple-vagrant-vms-in-one-vagrantfile/

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  # boxes at https://atlas.hashicorp.com/search.
  # config.vm.box = "ubuntu/trusty64"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.10.14"

  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "ubuntu/trusty64"    
    nginx.vm.hostname = 'nginx'
    nginx.vm.network :private_network, ip: "192.168.56.104"

    nginx.vm.provider :virtualbox do |v|
      # v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "nginx"]
    end

    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt -y install nginx
      sudo rm /etc/nginx/nginx.conf
      sudo cp /vagrant/nginx.conf /etc/nginx/nginx.conf
      sudo service nginx restart
    SHELL
  end


end
